### ISSUE TITLE
Support passpahrase input

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm#2073]

**Comment by cayenne17** [comment]
Hello, 
it is planned for when ?

**Comment by cayenne17** [comment]
I am in version 1.16.21 of Electerm and the problem is still present.

Here is the message I have: 
error
Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given

![image](https://user-images.githubusercontent.com/47927025/137586670-16b064b0-e384-4e09-8ea2-f599d359f70e.png)

**Comment by zxdong262** [comment]
@cayenne17 Not yet, should not close it

**Comment by zxdong262** [comment]
latest release already support
