### ISSUE TITLE
elcterm.app can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by cnsitk** [electerm/electerm#2619]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.22.30-mac-x64.dmg

### Platform detail (平台详情)

Darwin CNSITK-MAC.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.Download the electerm-1.22.30-mac-x64.dmg from https://github.com/electerm/electerm/releases
2.Double click to Install
3.Tyy to Open the electerm  

### What should have happened?(期望的结果)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/19630036/187009271-9e16a355-06c8-4fb2-a04d-881880ab2583.png">

**Comment by zxdong262** [comment]
软件是已经签名的，估计是跟你本机环境有关，是不是有什么安全设置或者网络原因？

**Comment by beta101-2022** [comment]
第一次要从安装文件夹里点打开，不能在应用打开。已经解决了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ZHAO ***@***.***> |
| 日期 | 2023年03月09日 20:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [electerm/electerm] elcterm.app can't be opened because Apple cannot check it for malicious software (Issue #2619) |

mac版本：Darwin MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct 9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64 我也遇到这个问题

最新版electerm吗？

**Comment by HanZhang-ZERO** [comment]
这个方法管用
https://support.apple.com/en-hk/guide/mac-help/mchleab3a043/mac

> ### Electerm Version and download file extension(Electerm版本和下载文件后缀)
> electerm-1.22.30-mac-x64.dmg
> 
> ### Platform detail (平台详情)
> Darwin CNSITK-MAC.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
> 
> ### What steps will reproduce the bug?(重新问题的详细步骤)
> 1.Download the electerm-1.22.30-mac-x64.dmg from https://github.com/electerm/electerm/releases 2.Double click to Install 3.Tyy to Open the electerm
> 
> ### What should have happened?(期望的结果)
> <img alt="image" width="265" src="https://user-images.githubusercontent.com/19630036/187009271-9e16a355-06c8-4fb2-a04d-881880ab2583.png">
> 
> ### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)
> _No response_
> 
> ### Additional information(其他任何相关信息)
> _No response_

**Comment by zxdong262** [comment]
> 软件是已经签名的，估计是跟你本机环境有关，是不是有什么安全设置或者网络原因？

好像我构建时候签名失败了，得研究一下
