### ISSUE TITLE
Subcategories/tree in bookmarks

### ISSUE THREAD

**Issue by vashkevichm** [electerm/electerm#964]
## Suggestions?
Could you please release subcategories/multiple tree in bookmarks

**Comment by zxdong262** [comment]
Hi @vashkevichm, Sure, other user mentions this feature too, see https://github.com/electerm/electerm/issues/701, unfortunately due to limited time I have, I am not sure when will I finish it, but I am sure it will be done anyway.

Thank you for the feedback, if you have any thought, just tell me, comment or submit a new issue. This project would not get this far without users's feedback.

**Comment by zxdong262** [comment]
@vashkevichm Released a new version with subcategories support.
